### ISSUE TITLE
Sort output matrix by order in the list. (enhancement)

### ISSUE THREAD

**Issue by Muilton** [maximtrp/scikit-posthocs#30]
Hello, author!
Thank you for great package. Great work! 

I would like to offer you to implement feature "sort" in test which help sort columns and rows in the output matrix by order in the list (which we push in sort)

for example, 
input: scikit-posthocs.posthoc_dunn(df, val_col='value', group_col='group', sort=['group_7', 'group_11', 'group_3'])
result:
                    group_7  group_11   group_3                          
group_7            -1             0.5            0.5
group_11         0.5              -1             0.5
group_3            0.5              0.5            -1

* colums and rows in the right order

* sorry, i don't know how to change label on enhancement
thanks

**Comment by maximtrp** [comment]
Hey! I think the correct way to do it is something like:

```python
import pandas as pd
import numpy as np
import scikit_posthocs as sp

df = pd.DataFrame.from_dict({'groups': ['c','a','b']*5, 'values': np.random.randint(0, 5, 15)})
df.groups = pd.Categorical(df.groups, categories=['c', 'b', 'a'], ordered=True)
sp.posthoc_dunn(df, val_col='values', group_col='groups', sort=True)
```

Sorting groups inside every post hoc function is redundant. So it is you who should sort the data before using it as an input. The issue is that scikit-posthocs currently does not respect an ordered `Categorical` dtype. The next release will include the fix. Thank you!
